language: python

addons:
     chrome: stable

dist: trusty
env:
    - DJANGO_VERSION=1.7.8
    - DJANGO_VERSION=1.8.2

before_install:
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost

install:
    - pip install -r robot/requirements.txt

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
    - rackup  # start a Web server
    - sleep 3 # give Web server some time to bind to sockets, etc
    - python3 -m http.server

script:
    - pybot robot
